defaults:  
  - _self_

### basic setting
#inFile: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/IE-inputs/AVERTIUM/akira.json
CTI_Source: AVERTIUM
inSet: dataset/IE-inputs
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ4/DemoNum/4

### openAI setting
model: qwen-plus
api_key: sk-47f2d862adf74ade822f5db3c5a6a2c1
#model: gpt-4o-mini
#api_key: sk-JK0wel63Y0VfNVw57e1a9d23Cb3941D28c29769612100f16
### demonstration setting
retriever:
  type: "kNN" #retriever type
  permutation: asc #the permutation of the kNN
shot: 4 #k of the kNN
demo_set: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/RE-IE-outputs-3-asc #store the demos(also the current ground truth)

### prompt setting
ie_prompt_set: Toolbox/IE_Prompts #the folder stored the prompt templates 
templ: QD1.jinja #used promt template
ie_prompt_store: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ2/DemoNum/4/prompt_store #store the prompt used for each CTI report